AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 80 Garnet Street Strata infrastructure

Parameters:
  DeployEnv:
    Type: String
  PinpointProjectId:
    Type: String

Resources:
#  LambdaCommonLayer:
#    Type: AWS::Serverless::LayerVersion
#    Properties:
#      ContentUri: ./LambdaCommonLayer
#      RetentionPolicy: Delete

  SendNotice:
    Type: AWS::Serverless::Function
    Properties:
      Description: Sends a notice to the specified endpoints
      Runtime: python3.8
      CodeUri: ./SendNotice
      Handler: app.lambda.handler
      Role: !GetAtt 'SendNoticeRole.Arn'
#      Layers:
#        - !Ref LambdaCommonLayer
      Timeout: 8
      MemorySize: 128
      Environment:
        Variables:
          DEPLOY_ENV: !Ref DeployEnv
          PINPOINT_PROJECT_ID: !Ref PinpointProjectId
          DISTRIBUTION_LIST_TABLE_NAME: !Ref 'DistributionList'
  SendNoticeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ['lambda.amazonaws.com']
            Action: ['sts:AssumeRole']
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:BatchGetItem
                  - dynamodb:GetItem
                  - dynamodb:Scan
                Resource:
                  - !GetAtt "DistributionList.Arn"
              - Effect: Allow
                Action: ['mobiletargeting:SendMessages']
                Resource:
                  - !Sub "arn:${AWS::Partition}:mobiletargeting:${AWS::Region}:${AWS::AccountId}:apps/${PinpointProjectId}/messages"

  DistributionList:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: DestinationAddress
          AttributeType: S
      KeySchema:
        - AttributeName: DestinationAddress
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      SSESpecification:
        SSEEnabled: TRUE
